//ADDME: CREATE A SCRIPT TO CHECK IF THE REQUIREMENTS ARE MET
//		 THEN IF THEY'RE MET, IF THE PLAYER PRESSES THE SWITCH BUTTON
// 		 THIS SCRIPT WILL STORE STAT POS ETC OF BOTH THE PARTIES:
//		 THE CHARACTER THE PLAYER HAS POSSESSION OF (DEFAULT KEVIN)
//		 AND THE CHARACTER WHOSE PLACE IS BEING TAKEN
// 		 THEN SWITCH SPRITES AND SHIT