# Generated using https://godot-build-options-generator.github.io
#18,3 mb on 3.3 vs 17,6 on 3.2.3
#17,8 mb on win
#18,3 -> 6,6 MB on linux with UPX
#17,8 -> 6,2 MB on win with UPX
# experimenting removing GLES2
# don't uncomment the ones with yes or it's gonna take a way longer time compiling and more space, somehow.

target                         = "release"
bits                           = "64"

tools                          = "no"
disable_3d                     = "yes"

optimize                       = "size"
deprecated                     = "no"
#minizip = "yes"
module_bmp_enabled             = "no"
module_bullet_enabled          = "no"
module_camera_enabled          = "no"
module_csg_enabled             = "no"
module_cvtt_enabled            = "no"
module_dds_enabled             = "no"
module_denoise_enabled         = "no"
module_enet_enabled            = "no"
module_etc_enabled             = "no"
module_fbx_enabled             = "no"
#module_freetype_enabled        = "yes"
module_gdnative_enabled        = "no"
#module_gdscript_enabled        = "yes"
module_gdnavigation_enabled    = "no"
module_gridmap_enabled         = "no"
module_hdr_enabled             = "no"
module_jpg_enabled             = "no"
module_jsonrpc_enabled         = "no"
module_lightmapper_cpu_enabled = "no"
module_mbedtls_enabled         = "no"
module_minimp3_enabled         = "no"
module_mobile_vr_enabled       = "no"
module_mono_enabled            = "no"
module_ogg_enabled             = "no"
module_opensimplex_enabled     = "no"
module_opus_enabled            = "no"
module_pvr_enabled             = "no"
module_raycast_enabled         = "no"
module_recast_enabled          = "no"
#module_regex_enabled           = "yes"
module_squish_enabled          = "no"
#module_stb_vorbis_enabled      = "yes"
module_svg_enabled             = "no"
module_tga_enabled             = "no"
module_theora_enabled          = "no"
module_tinyexr_enabled         = "no"
module_upnp_enabled            = "no"
module_vhacd_enabled           = "no"
module_visual_script_enabled   = "no"
module_vorbis_enabled          = "no"
module_webm_enabled            = "no"
module_webp_enabled            = "no"
module_webrtc_enabled          = "no"
module_websocket_enabled       = "no"
module_webxr_enabled           = "no"
module_xatlas_unwrap_enabled   = "no"
